version = 0.1.0
java_name = cascara.lang.java
maven_name = cascara-lang-java
group = io.github.qishr
title = Cascara Java Tokenizer
description = Cascara Java language processors.
url = https://qishr.github.io/javadoc/cascara.lang.java/
scm_url = https://github.com/qishr/cascara-lang-java
scm_conn = scm:git:https://github.com/qishr/cascara-lang-java.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-lang-java.git

org.gradle.configuration-cache = false


